mvccore/Models/ErrorViewModel.cs
using System;

namespace mvccore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mvccore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Logging;
using mvccore.Models;

namespace mvccore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var model = new ErrorViewModel();
            model.RequestId = "999";
            ViewBag.aa = "张三";
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult ceshi()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult Login(Users model)
        {
            if (string.IsNullOrWhiteSpace(model.UserName) || string.IsNullOrWhiteSpace(model.PassWord))
            {

                return Content("<script>alert('账号或密码不能为空！');history.go(-1);</script>");

            }
            if (model.UserName == "1" && model.PassWord == "1")
            {

                //return new RedirectResult("privacy");
                return Ok("/boostrapIndex/boostrapIndex");
                //return RedirectToAction("boostrapIndex", "boostrapIndex");
                //return RedirectToPage("home/privacy");
                //return RedirectToAction("privacy");
                //HttpContext.Response.Redirect("./home/privacy");
                //return "成功";
            }
            else
            {
                return Content("<script>alert('账号或密码错误！！！');history.go(-1);</script>");
            }
        }

        public class Users
        {
            public string UserName { get; set; }
            public string PassWord { get; set; }
        }    
    }
}

mvccore/Controllers/JwtController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace mvccore.Controllers
{
    //[Authorize] 特性用于标识此 Controller 或 Action 需要使用合规的 Token 才能登录
    [Route("api/[Controller]")]
    [ApiController]
    public class JwtController : ControllerBase
    {
        [Authorize]
        [HttpGet("get")]
        public string Get()
        {
            return "访问成功";
        }

        [HttpGet("Token")]
        public string Token()
        {
           return Program.ConsoleToke();
        }

    }
}

mvccore/Controllers/bootstrap/boostrapIndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace mvccore.Views.bootstrap
{
    public class boostrapIndexController : Controller
    {
        public IActionResult boostrapIndex()
        {

            ViewBag.aa = "a";
            return View();
        }

        public IActionResult Index()
        {      
            return View();
        }
    }
}

mvccore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var ss = Model;
}

<script src="~/js/jquery-1.7.1.min.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<script src="~/bootstrap/css/bootstrap.min.css"></script>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core"> @ss.RequestId</a>.</p>
    <p>@ViewBag.aa</p>
    <div class="input-group   input-group-sm">
        <span class="input-group-addon"></span>
        <input type="text" class="form-control" id="username" placeholder="username" value="">
    </div>
    <div class="input-group   input-group-sm">
        <span class="input-group-addon"></span>
        <input type="password" class="form-control" id="password" placeholder="password" value="">
    </div>
    <div class="btn-group btn-group-lg">
        <button type="button" id="login" class="btn btn-default">登录</button>
    </div>
    <form action="/Home/Login" method="post">
        <input type="text" name="username" /><br /><br />
        <input type="password" name="password" /><br /><br />
        <input type="submit" value="登入" />
        <input type="text" id="ser_Sms_serachText" />
    </form>

    <input type="button" name="name" id="gettoken" value="获取Token" />
    <input type="button" name="name" id="checktoken" value="验证Token" />
    <input type="text" name="name" id="tokenvaue" value="" />
    <script>

        var token = "";
        $("#login").click(function () {
            $.ajax({
          url: '@Url.Action("Login", "Home")',
            type: "post",
                //dataType: "json",
                    data: {
                        username: $("#username").val(),
                        password: $("#password").val(),
                    },
                    success: function (data) {

                        if (data) {
                            window.location.href = data;
                            //data = JSON.parse(data);
                            //alert(data);
                        }
                    }
        });

        });

        $("#gettoken").click(function () {
            $.ajax(
                {

          url: '@Url.Action("Token", "Jwt")',
            type: "get",
                //dataType: "json",
                    success: function (data) {

                        if (data) {

                            token = data;
                            //data = JSON.parse(data);
                            alert(token);
                        }
                    }
        });

        });


        $("#checktoken").click(function () {
            $.ajax({
                url: "/api/Jwt/GET",
                headers: { "Authorization": "Bearer " + token },
                data: { token: token },
                type: "get",
                async: false,
                success: function (e) {
                    alert(JSON.stringify(e));
                }, error: function (e) {
                    alert(e.status);
                }
            });
        });

    </script>
</div>

mvccore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvccore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvccore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - mvccore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

mvccore/Views/boostrapIndex/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>首页</title>
        <script src="~/js/jquery-1.7.1.min.js"></script>
        <script src="~/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/bootstrap/css/bootstrap.min.css"></script>
    </head>
    <body>
        <div>
            <h1>Index</h1>








        </div>
    </body>
    </html>

mvccore/Views/boostrapIndex/boostrapIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>@ViewBag.aa</title>
        <script src="~/js/jquery-1.7.1.min.js"></script>
        <script src="~/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/bootstrap/css/bootstrap.min.css"></script>
    </head>
    <body>
        <div>
            <div class="input-group   input-group-sm">
                <span class="input-group-addon"></span>
                <input type="text" class="form-control" id="username" placeholder="username" value="">
            </div>
            <div class="input-group   input-group-sm">
                <span class="input-group-addon"></span>
                <input type="password" class="form-control" id="password" placeholder="password" value="">
            </div>
            <div class="btn-group btn-group-lg">
                <button type="button" id="login" class="btn btn-default">登录</button>
            </div>

        </div>
    </body>
    </html>